
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[363] =
    {   0,
       50,   50,   55,   54,   53,   52,   54,    2,   50,   49,
       49,    1,    5,    6,   54,   54,    3,    4,    0,   48,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   50,   50,   50,
       49,    0,    0,    0,   48,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   20,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   51,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,   17,    0,    0,    0,    0,
        0,    0,   46,   38,    0,    0,    0,    0,    0,    0,
        0,   33,    0,    0,   18,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,   25,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   34,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    8,    0,
        0,    0,    0,    0,   47,    0,    0,    0,    0,   11,
        0,    0,    0,    0,   31,    0,    0,    0,    0,   30,
       32,    0,    0,    0,    0,    0,    0,    0,    0,   24,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,    0,    0,    0,    0,   21,    0,   10,
       27,    0,    0,    0,    0,    0,    0,   40,    0,    0,
        0,    0,    0,   44,    0,    0,   39,    0,   13,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   43,    0,   41,    0,    0,    0,    0,    0,    0,
       35,   12,    0,    0,    0,   23,    0,    0,    0,   14,
        0,    0,    0,    0,   26,    0,   42,    0,    0,    0,
        0,    0,    0,    0,    0,   36,    0,    0,    0,    0,
        0,    0,   16,    0,    0,   19,   29,    0,   37,    0,
       28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    1,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    1,    1,
        1,    1,    1,    1,    1,   10,   11,   12,   13,    1,
        1,   14,   15,    1,    1,    1,    1,   16,   17,   18,
        1,    1,   19,   20,    1,    1,    1,    1,    1,    1,
       21,   22,   23,    1,    1,    1,   24,   25,   26,   27,

       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,    1,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,    1,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[366] =
    {   0,
        0,   48,   83, 1043, 1043, 1043,   94, 1043,    3,    6,
        9, 1043, 1043, 1043,   52,   36, 1043, 1043,   14, 1043,
       16,   38,   21,   22,   62,   41,   57,   58,   70,   78,
       64,  100,  109,  123,  129,   83,  137,   20,   23,   26,
      100,   36,   25,   18,   95,  136,  140,  143,  145,  149,
      151,  152,  168,  172,  174,  173,  176,  181,  179,  184,
      185,  187,  188,  196,  201,  215,  204,  218,  220,  221,
      225,  226,  227,    7,   11,  237,  249,  250,  251,  254,
      256,  260,  263,  265,  266,  271,  276,  273,  279,  277,
      286, 1043,  293,  296,  299,  302,  305,  312,  306,  316,

      319,  322,  329,  331,  343,  333,  352,  354,    9, 1043,
      344,  355,  356,  357,  360,  364,  367,  377,  379,  384,
      381,  391,  394,  393,  404,  407,  408,  413,  415,  417,
      419,  424,  420,  421,  428,  436,  440,  441,  448,  449,
      451,  455,  456,  457,  464,  470,  476,  477,  478,  484,
      485,  487,  491,  497,  508,  492,  500,  504,  512,  520,
      521,  525,  529,  533, 1043, 1043,  534,  536,  540,  541,
      542,  545, 1043, 1043,  546,  565,  568,  569,  571,  570,
      573, 1043,  576,  577, 1043,  578,  581,  585,  592,  593,
      600,  601,  590,  607,  609, 1043, 1043,  612,  616,  624,

      623,  626,  629,  635,  636,  638,  628,  637,  645,  652,
      659,  662,  664,  666,  668, 1043, 1043,  671,  673,  674,
      678,  679,  683,  687,  690,  693, 1043,  700, 1043,  704,
      712,  717,  721,  719, 1043,  720,  723,  726,  731, 1043,
      733,  734,  736,  746, 1043,  740,  743,  756,  759, 1043,
     1043,  747,  762,  767,  768,  769,  770,  772,  778, 1043,
      781,  783,  784,  789,  791,  792,  800,  805,  806,  812,
     1043,  816,  817,  819,  820,  822,  827, 1043,  825, 1043,
     1043,  832,  839,  841,  842,  844,  847, 1043,  852,  848,
      853,  864,  867, 1043,  869,  874, 1043,  877, 1043,  878,

      879,  883,  886,  888,  889,  894,  890,  899,  902,  909,
      905, 1043,  913, 1043,  914,  918,  919,  921,  925,  928,
     1043, 1043,  933,  934,  935, 1043,  941,  945,  948, 1043,
      955,  956,  957,  961, 1043,  962, 1043,  967,  969,  971,
      976,  977,  986,  988,  990, 1043,  991,  997, 1000, 1002,
     1001, 1003, 1043, 1005, 1010, 1043, 1043, 1012, 1043, 1014,
     1043, 1043,   34,   23,    0
    } ;

static const flex_int16_t yy_def[366] =
    {   0,
      363,  363,  362,  362,  362,  362,  364,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  364,  362,
      365,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  362,  362,  362,
      362,  362,  362,  364,  364,  365,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  362,  362,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  362,  364,  364,  364,  364,  364,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  362,  362,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  362,  362,  364,  364,  364,  364,
      364,  364,  362,  362,  364,  364,  364,  364,  364,  364,
      364,  362,  364,  364,  362,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  362,  362,  364,  364,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  362,  362,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  362,  364,  362,  364,
      364,  364,  364,  364,  362,  364,  364,  364,  364,  362,
      364,  364,  364,  364,  362,  364,  364,  364,  364,  362,
      362,  364,  364,  364,  364,  364,  364,  364,  364,  362,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      362,  364,  364,  364,  364,  364,  364,  362,  364,  362,
      362,  364,  364,  364,  364,  364,  364,  362,  364,  364,
      364,  364,  364,  362,  364,  364,  362,  364,  362,  364,

      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  362,  364,  362,  364,  364,  364,  364,  364,  364,
      362,  362,  364,  364,  364,  362,  364,  364,  364,  362,
      364,  364,  364,  364,  362,  364,  362,  364,  364,  364,
      364,  364,  364,  364,  364,  362,  364,  364,  364,  364,
      364,  364,  362,  364,  364,  362,  362,  364,  362,  364,
      362,    0,  362,  362,  362
    } ;

static const flex_int16_t yy_nxt[1093] =
    {   0,
       44,    5,    6,    7,    8,    9,   10,   11,   12,   38,
       38,   39,   40,   40,   39,   41,   41,   20,   19,   45,
       13,   20,   14,   19,   20,   20,   38,   38,   15,   38,
       38,   39,   40,   40,    4,   21,  110,   46,  110,   21,
       16,   20,   21,   21,   20,   52,  109,   17,   18,    5,
        6,    7,    8,    9,   10,   11,   12,   51,   53,   21,
       20,   20,   21,   47,   48,   20,   75,   20,   13,   74,
       14,   57,   49,   20,   43,   42,   15,   50,   21,   21,
       58,   20,  362,   21,   59,   21,   20,   60,   16,   54,
      362,   21,   55,   61,   64,   17,   18,   20,   20,   21,

       56,   62,  362,   20,   21,   39,   41,   41,   63,  362,
      362,  362,   20,   71,  362,   21,   21,   22,   23,   24,
       25,   21,   26,   27,   28,   29,   20,   30,   31,   32,
       21,   33,   20,   34,   35,  362,   36,   37,   19,   45,
       20,   65,  362,   20,   21,  362,   20,   66,   20,  362,
       21,  362,   20,   67,   20,   20,  362,   46,   21,   68,
       72,   21,  362,   69,   21,   70,   21,   73,  362,   77,
       21,   20,   21,   21,   79,   20,   20,   20,  362,   20,
       76,   78,   92,  362,   20,  362,   80,   20,   20,   21,
       20,   20,   81,   21,   21,   21,   88,   21,  362,   20,

       21,   82,   21,   83,   20,   21,   21,   20,   21,   21,
       94,   84,   85,   86,   89,   91,   87,   21,   20,   93,
       90,   20,   21,   20,   20,   21,   95,   96,   20,   20,
       20,   97,  362,  362,   98,   99,   21,  362,  362,   21,
       20,   21,   21,  104,  362,  100,   21,   21,   21,  362,
      102,  101,   20,   20,   20,  107,  103,   20,   21,   20,
      362,  105,  108,   20,  106,  112,   20,  111,   20,   20,
       21,   21,   21,  362,   20,   21,   20,   21,  114,   20,
       20,   21,   20,  116,   21,  362,   21,   21,  362,   20,
      119,  113,   21,  120,   21,  115,   20,   21,   21,   20,

       21,  117,   20,  118,  125,   20,  122,   21,   20,   20,
      362,  121,  362,  126,   21,   20,  123,   21,  124,   20,
       21,  362,   20,   21,  362,   20,   21,   21,  128,  127,
      133,  362,   20,   21,   20,  131,   20,   21,  362,  129,
       21,  134,  130,   21,  362,  132,   20,   20,  362,  137,
       21,  362,   21,  362,   21,   20,  136,   20,   20,   20,
       20,  362,  135,   20,   21,   21,  140,   20,  362,  138,
       20,  139,  362,   21,  141,   21,   21,   21,   21,  142,
       20,   21,   20,  362,   20,   21,  144,   20,   21,  143,
      145,  146,  147,  149,   20,  362,   20,   20,   21,  148,

       21,  150,   21,  156,  151,   21,  152,   20,  157,  153,
       20,   20,   21,  158,   21,   21,   20,  155,  165,  154,
      166,  161,   20,   20,   20,   21,  162,   20,   21,   21,
      160,   20,  362,  159,   21,  362,   21,  168,   21,   20,
       21,   21,   21,  173,  174,   21,  163,  169,  170,   21,
      164,   20,   20,  167,   20,  171,  362,   21,   20,   20,
       20,   21,   21,  172,  362,  362,  362,  182,  362,   21,
       21,  362,   21,   20,  177,  362,   21,   21,   21,   20,
      185,   20,  176,  179,  181,   21,  180,   20,   20,  175,
       20,   21,  362,  178,   20,   20,  362,   21,   21,   21,

       20,  362,  184,   20,  362,   21,   21,   20,   21,  362,
      183,   20,   21,   21,  186,  196,  362,  362,   21,  187,
      188,   21,  189,  197,   20,   21,  194,  191,   20,   21,
      193,  190,   20,   21,  195,  192,   20,   20,  362,   20,
      362,   21,   21,   20,   20,   20,   21,  198,   20,   20,
       21,  362,  206,  362,   21,   21,  200,   21,  205,  203,
      362,   21,   21,   21,  362,  362,   21,   21,   20,  201,
      199,   20,   20,   20,   20,  202,  216,  209,  204,  217,
       20,   20,  210,  207,   20,  208,   21,  212,   20,   21,
       21,   21,   21,   20,   21,   20,   20,   21,   21,   21,

      362,  211,   21,   20,   20,  215,   21,  218,  213,  214,
      227,   21,   20,   21,   21,  229,  219,  226,  222,   20,
      220,   21,   21,  223,  224,  221,   20,   20,   21,   20,
       21,   20,   20,   21,  231,  362,  225,   21,  235,   20,
      240,   20,  362,  228,   21,   21,  362,   21,   20,   21,
       21,  236,  362,  230,  362,   20,   21,   21,   21,   21,
      233,  238,   20,  232,  234,   20,   21,  245,  239,   20,
      243,   20,  237,   21,   20,  242,   20,  250,  241,  362,
       21,  251,   20,   21,  362,   21,   20,   21,  362,   21,
       20,  362,   21,   20,   21,   21,   20,  247,  362,   21,

       21,  362,  244,   20,   21,  246,  248,   20,   21,  252,
      362,   21,  362,  362,   21,   20,  256,  362,  249,  253,
      260,   21,   20,   20,   20,   21,   20,  257,  254,   20,
      255,  258,  261,   21,   20,  259,   20,   20,   21,   20,
       21,   21,   21,  271,   21,  262,   20,   21,  263,   20,
       20,  362,   21,  264,   21,   21,  362,   21,  272,   20,
      267,   21,   20,  268,   21,   20,  265,   21,   21,  270,
       20,  278,   20,  280,  269,  281,  266,   21,  274,  362,
       21,   20,  275,   21,   20,  273,   20,   20,   21,   21,
       21,   21,   20,   21,   20,  288,  285,  276,  362,   21,

      362,  279,   21,   20,   21,   21,  362,  277,   20,   20,
       21,  283,   21,   21,  362,   20,  284,  282,  287,   20,
      294,   21,   20,   20,  286,  297,   21,   21,  299,  291,
       20,  362,  290,   21,  289,   20,  362,   21,   21,  362,
       21,   21,   20,   21,   20,   20,   21,   20,   21,  296,
       20,   20,  292,   21,  298,   20,   20,  293,  362,  300,
       21,  362,   21,   21,  295,   21,  362,   20,   21,   21,
       20,  302,   20,   21,   21,  303,  305,  312,  301,  306,
       20,  314,   20,  362,  304,   21,   20,  307,   21,   20,
       21,   20,   20,  321,  309,   21,  308,   20,   21,   21,

       21,  310,  322,  313,   21,   20,  311,   21,   20,   21,
       21,   21,   20,  317,  362,   21,  326,   20,  316,  315,
       21,   20,   20,   21,  330,  319,   21,  318,   20,  320,
       21,   20,  325,  324,   21,   21,   20,   20,  335,   21,
       21,  323,   21,  362,   20,  362,   21,  328,  337,   21,
      362,   20,  327,  329,   21,   21,   21,  362,   20,   20,
       20,  334,   21,  331,   20,   20,   21,  362,  332,   21,
       20,  336,   20,  333,  346,  338,   21,   21,   21,   20,
       20,  362,   21,   21,  362,  339,  343,  341,   21,   20,
       21,   20,   21,   20,   20,  340,  345,   21,   21,  342,

      353,  347,  344,   20,  356,   20,  357,   21,   20,   21,
      362,   21,   21,  359,  362,   20,  348,  361,   21,  362,
      362,   21,   21,   21,   21,  362,   21,  349,  350,  351,
      352,   21,  358,   21,  362,   21,  362,  362,  360,  362,
      354,  355,    3,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362

    } ;

static const flex_int16_t yy_chk[1093] =
    {   0,
      365,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        9,   10,   10,   10,   11,   11,   11,   19,   21,   21,
        1,   44,    1,  364,   23,   24,   38,   38,    1,   39,
       39,   40,   40,   40,  363,   19,  109,   21,   75,   44,
        1,   22,   23,   24,   26,   24,   74,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,   23,   24,   22,
       27,   28,   26,   22,   22,   25,   43,   31,    2,   42,
        2,   26,   22,   29,   16,   15,    2,   22,   27,   28,
       27,   30,    3,   25,   28,   31,   36,   28,    2,   25,
        0,   29,   25,   29,   31,    2,    2,    7,   45,   30,

       25,   30,    0,   32,   36,   41,   41,   41,   30,    0,
        0,    0,   33,   36,    0,    7,   45,    7,    7,    7,
        7,   32,    7,    7,    7,    7,   34,    7,    7,    7,
       33,    7,   35,    7,    7,    0,    7,    7,   46,   46,
       37,   32,    0,   47,   34,    0,   48,   33,   49,    0,
       35,    0,   50,   34,   51,   52,    0,   46,   37,   34,
       37,   47,    0,   34,   48,   35,   49,   37,    0,   48,
       50,   53,   51,   52,   50,   54,   56,   55,    0,   57,
       47,   49,   59,    0,   58,    0,   51,   60,   61,   53,
       62,   63,   52,   54,   56,   55,   56,   57,    0,   64,

       59,   53,   58,   53,   65,   60,   61,   67,   62,   63,
       61,   54,   55,   55,   57,   58,   55,   64,   66,   60,
       57,   68,   65,   69,   70,   67,   62,   63,   71,   72,
       73,   64,    0,    0,   65,   65,   66,    0,    0,   68,
       76,   69,   70,   69,    0,   66,   71,   72,   73,    0,
       67,   66,   77,   78,   79,   72,   68,   80,   76,   81,
        0,   70,   73,   82,   71,   77,   83,   76,   84,   85,
       77,   78,   79,    0,   86,   80,   88,   81,   79,   87,
       90,   82,   89,   81,   83,    0,   84,   85,    0,   91,
       84,   78,   86,   85,   88,   80,   93,   87,   90,   94,

       89,   82,   95,   83,   90,   96,   87,   91,   97,   99,
        0,   86,    0,   91,   93,   98,   88,   94,   89,  100,
       95,    0,  101,   96,    0,  102,   97,   99,   94,   93,
       99,    0,  103,   98,  104,   97,  106,  100,    0,   95,
      101,  100,   96,  102,    0,   98,  105,  111,    0,  102,
      103,    0,  104,    0,  106,  107,  101,  108,  112,  113,
      114,    0,  100,  115,  105,  111,  105,  116,    0,  103,
      117,  104,    0,  107,  106,  108,  112,  113,  114,  107,
      118,  115,  119,    0,  121,  116,  111,  120,  117,  108,
      112,  113,  114,  116,  122,    0,  124,  123,  118,  115,

      119,  117,  121,  123,  118,  120,  119,  125,  123,  120,
      126,  127,  122,  123,  124,  123,  128,  122,  129,  121,
      130,  126,  131,  133,  134,  125,  126,  132,  126,  127,
      125,  135,    0,  124,  128,    0,  129,  132,  130,  136,
      131,  133,  134,  137,  138,  132,  127,  133,  134,  135,
      128,  139,  140,  131,  141,  135,    0,  136,  142,  143,
      144,  137,  138,  136,    0,    0,    0,  145,    0,  139,
      140,    0,  141,  146,  141,    0,  142,  143,  144,  147,
      148,  149,  140,  143,  144,  145,  143,  150,  151,  139,
      152,  146,    0,  142,  153,  156,    0,  147,  148,  149,

      154,    0,  147,  157,    0,  150,  151,  158,  152,    0,
      146,  155,  153,  156,  149,  159,    0,    0,  154,  150,
      151,  157,  152,  160,  161,  158,  157,  154,  162,  155,
      156,  153,  163,  159,  158,  155,  164,  167,    0,  168,
        0,  160,  161,  169,  170,  171,  162,  161,  172,  175,
      163,    0,  171,    0,  164,  167,  163,  168,  170,  168,
        0,  169,  170,  171,    0,    0,  172,  175,  176,  164,
      162,  177,  178,  180,  179,  167,  181,  176,  169,  183,
      184,  186,  176,  172,  187,  175,  176,  178,  188,  177,
      178,  180,  179,  193,  181,  189,  190,  183,  184,  186,

        0,  177,  187,  191,  192,  180,  188,  184,  178,  179,
      194,  193,  195,  189,  190,  198,  186,  193,  189,  199,
      187,  191,  192,  190,  191,  188,  201,  200,  194,  202,
      195,  207,  203,  198,  200,    0,  192,  199,  204,  205,
      208,  206,    0,  195,  201,  200,    0,  202,  209,  207,
      203,  204,    0,  199,    0,  210,  204,  205,  208,  206,
      202,  206,  211,  201,  203,  212,  209,  213,  207,  214,
      211,  215,  205,  210,  218,  210,  219,  220,  209,    0,
      211,  221,  222,  212,    0,  213,  223,  214,    0,  215,
      224,    0,  218,  225,  219,  220,  226,  215,    0,  221,

      222,    0,  212,  228,  223,  214,  218,  230,  224,  222,
        0,  225,    0,    0,  226,  231,  226,    0,  219,  223,
      232,  228,  234,  236,  233,  230,  237,  228,  224,  238,
      225,  230,  233,  231,  239,  231,  241,  242,  232,  243,
      234,  236,  233,  246,  237,  234,  247,  238,  236,  244,
      252,    0,  239,  237,  241,  242,    0,  243,  247,  248,
      241,  246,  249,  242,  247,  253,  238,  244,  252,  244,
      254,  255,  256,  257,  243,  258,  239,  248,  249,    0,
      249,  259,  252,  253,  261,  248,  262,  263,  254,  255,
      256,  257,  264,  258,  265,  266,  263,  253,    0,  259,

        0,  256,  261,  267,  262,  263,    0,  254,  268,  269,
      264,  261,  265,  266,    0,  270,  262,  259,  265,  272,
      273,  267,  274,  275,  264,  276,  268,  269,  279,  269,
      277,    0,  268,  270,  267,  282,    0,  272,  273,    0,
      274,  275,  283,  276,  284,  285,  279,  286,  277,  275,
      287,  290,  270,  282,  277,  289,  291,  272,    0,  282,
      283,    0,  284,  285,  274,  286,    0,  292,  287,  290,
      293,  284,  295,  289,  291,  285,  287,  296,  283,  289,
      298,  300,  301,    0,  286,  292,  302,  290,  293,  303,
      295,  304,  305,  307,  292,  296,  291,  306,  298,  300,

      301,  293,  308,  298,  302,  309,  295,  303,  311,  304,
      305,  307,  310,  303,    0,  306,  313,  315,  302,  301,
      308,  316,  317,  309,  318,  305,  311,  304,  319,  306,
      310,  320,  311,  310,  313,  315,  323,  324,  325,  316,
      317,  309,  318,    0,  327,    0,  319,  316,  328,  320,
        0,  329,  315,  317,  323,  324,  325,    0,  331,  332,
      333,  324,  327,  319,  334,  336,  328,    0,  320,  329,
      338,  327,  339,  323,  340,  329,  331,  332,  333,  341,
      342,    0,  334,  336,    0,  331,  336,  333,  338,  343,
      339,  344,  340,  345,  347,  332,  339,  341,  342,  334,

      348,  341,  338,  349,  351,  350,  352,  343,  354,  344,
        0,  345,  347,  355,    0,  358,  342,  360,  348,    0,
        0,  349,  351,  350,  352,    0,  354,  343,  344,  345,
      347,  355,  354,  358,    0,  360,    0,    0,  358,    0,
      349,  350,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "kap.l"
#line 2 "kap.l"
#include <stdio.h>
#include <stdlib.h>
#include "kapabison.tab.h"
#include <string.h>
#include <unistd.h>
#define MAX_STR_CONST 1025
int line_num=1;
int line_init=-1;
char*str_buf[MAX_STR_CONST];    
char*str_buf_ptr;
#line 813 "lex.yy.c"
#line 814 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "kap.l"

#line 23 "kap.l"
 

#line 1036 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1043 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "kap.l"
{return COLON;}                     
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "kap.l"
{return COMMA;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "kap.l"
{return OBRACKETS;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "kap.l"
{return CBRACKETS;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "kap.l"
{return OBRACES;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "kap.l"
{return CBRACES;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 "kap.l"
{return last;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "kap.l"
{return gameId;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "kap.l"
{return drawId;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "kap.l"
{return drawTime;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "kap.l"
{return status;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "kap.l"
{return visualDraw;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "kap.l"
{return drawBreak;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "kap.l"
{return pricePoints;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "kap.l"
{return amount;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "kap.l"
{return winningNumbers;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "kap.l"
{return list;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "kap.l"
{return bonus;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "kap.l"
{return prizeCategories;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "kap.l"
{return id;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "kap.l"
{return divident;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "kap.l"
{return winners;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 "kap.l"
{return distributed;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 48 "kap.l"
{return jackpot;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 49 "kap.l"
{return fixed;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 50 "kap.l"
{return categoryType;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 51 "kap.l"
{return gameType;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 52 "kap.l"
{return minimumDistributed;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 53 "kap.l"
{return wagerStatistics;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 54 "kap.l"
{return columns;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 55 "kap.l"
{return wagers;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 56 "kap.l"
{return content;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 57 "kap.l"
{return addOn;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 58 "kap.l"
{return active;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 59 "kap.l"
{return totalPages;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 60 "kap.l"
{return totalElements;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 61 "kap.l"
{return numberOfElements;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 62 "kap.l"
{return sort;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 63 "kap.l"
{return direction;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 64 "kap.l"
{return property;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 65 "kap.l"
{return ignoreCase;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 66 "kap.l"
{return nullHandling;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 67 "kap.l"
{return descending;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 68 "kap.l"
{return ascending;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 69 "kap.l"
{return first;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 70 "kap.l"
{return size;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 71 "kap.l"
{return number;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 72 "kap.l"
{return STRING;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 "kap.l"
{return INT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 "kap.l"
{return FLOAT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 75 "kap.l"
{return BOOLEAN;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 79 "kap.l"
{++line_num;}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 80 "kap.l"
{;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "kap.l"
ECHO;
	YY_BREAK
#line 1366 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 362);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 82 "kap.l"



int yywrap(void)
{
  return 1;
  }
